version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ecg-dl-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hmd3fog4dmta"
s3_prefix = "ecg-dl-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["FastaiVisionFunction=096374906812.dkr.ecr.us-east-1.amazonaws.com/ecr-dl-lambda"]